services:
  - type: web
    name: daily-sms-service
    runtime: python
    region: oregon
    plan: standard
    buildCommand: ./build.sh
    startCommand: ./docker-entrypoint.sh web
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: POETRY_VERSION
        value: 1.6.1
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        sync: false
      - key: FLASK_APP
        value: src.features.web_app.code
      - key: DATABASE_URL
        fromDatabase:
          name: daily-sms-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: GUNICORN_WORKERS
        value: 2
      - key: GUNICORN_THREADS
        value: 4
      - key: GUNICORN_TIMEOUT
        value: 30
      - key: RENDER_DEPLOY_HOOK_SECRET
        sync: false
    autoDeploy: false
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

databases:
  - name: daily-sms-db
    region: oregon
    plan: standard
    ipAllowList: []
